---
title: On Blogging
date: "March 25, 2025"
author: "Anika Krishna"
---

In his book titled How to Be a Modern Scientist, Jeff Leek provides some interesting advice in the section “Scientific Blogging.” He begins by describing the benefits of creating a blog where one can show off their data visualization and storytelling skills, teach others how to do a certain analysis, or discuss a relevant topic in their industry. Leek also mentions that a blog can also be “just for fun,” meaning that one can use it to share personal projects or chronicle what they are currently learning, while still remaining professional. He states that this can be a way to achieve a sense of accomplishment in the short term to stay motivated while working on a longer project such as a thesis. However, he warns that there is an “energy tradeoff” between blogging and writing papers/doing research, so one should be careful to strike a balance that prevents burnout.

As the first blog post on my website, I chose to write about the topic of blogging because of how important I feel storytelling is within statistics. In my opinion, the best scientists share their work in multiple formats in order to make it accessible to a broader audience than just academics within their field. One of my favorite podcasts, “Stats + Stories,” has the tagline “the statistics behind the stories and the stories behind the statistics,” and combines journalism with math to produce meaningful and engaging content. In a recent episode, called “Chart Spark,” Allie Torbin, a data literacy advocate and expert in creative information design, shares similar advice to Leek, in describing the benefits of producing and sharing content outside of academic papers. She talks extensively about the concept of ‘creativity,’ emphasizing that though many are intimidated by the idea of being a “creative person,” the effort to remix existing ideas in an ethical manner is all one really needs to begin creating content. 

In the second half of his section on scientific blogging, Leek explores the nuances of receiving and responding to criticism online. He makes the point that nowadays, “everyone is an internet scientist,” and people are always looking for a good fight. He provides some options on how to deal with experiencing this type of criticism, ending the chapter by stating that, “all of this only applies if you write a paper that a ton of people care about/is controversial.” What he does not explicitly consider in this chapter is that given the turbulent nature of social media, almost anything can become controversial. One example of this is Dr. Ally Louks’ PhD dissertation, titled “Olfactory Ethics: The Politics of Smell in Modern and Contemporary Prose,” which went viral on X (formerly Twitter) in November of 2024, when she posted a picture of herself with her thesis to celebrate earning her doctorate. Instantly, she was bombarded with criticisms of her topic by those who felt it was unimportant, as well as even personal attacks and misogynistic comments. Despite this unexpected response, Louks reacted professionally, employing a combination of the 3 options Leek suggests (responding in internet time, responding in academic time, or not responding at all). After garnering so much attention, what started as criticism from internet trolls morphed into a larger portion of X users coming to her defense by finding ways to relate their own ideas and observations to her thesis. A microtrend arose of finding “olfactory ethics” everywhere, from popular media to daily life, thus modeling in real life Torbin’s idea of creativity as remixing existing ideas and Leek’s ideas related to extending the impact of one’s work by reaching non-academic communities.
